name: Update m3u8 links

on:
  schedule:
    - cron: '0 */5 * * *'   # every 5 hours
  workflow_dispatch:         # Still allows manual runs

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install chromium --with-deps

      - name: Run the script
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: python main.py
